// Regenerates the "Roles and permissions" table in README.md from lib/permissions.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { PERMISSIONS } from "../lib/permissions";

const roles = ["doctor", "nurse"] as const;
const rows = Object.values(PERMISSIONS).map(
  (p) => `| ${p.label} | ${roles.map((r) => ((p.roles as readonly string[]).includes(r) ? "yes" : "-")).join(" | ")} |`,
);
const table = ["| Action | Doctor | Nurse |", "| --- | --- | --- |", ...rows].join("\n");
const block = `<!-- permissions:start (generated by npm run permissions-table) -->\n${table}\n<!-- permissions:end -->`;

const readme = readFileSync("README.md", "utf8");
const re = /<!-- permissions:start[\s\S]*?<!-- permissions:end -->/;
writeFileSync("README.md", re.test(readme) ? readme.replace(re, block) : readme.replace("## Credits", `## Roles and permissions\n\n${block}\n\n## Credits`));
